name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_VER: 'v5.18.16'
      LINUX_PATH: 'linux'
      TARGET_PATH: 'kernel_aarch64'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Linux stable kernel
        uses: actions/checkout@v3
        with:
          repository: gregkh/linux
          ref: ${{ env.KERNEL_VER }}
          path: ${{ env.LINUX_PATH }}

      - name: Prepare build environment
        run: |
          sudo apt update -y
          sudo apt install gcc-aarch64-linux-gnu -y

          # gcc-aarch64-linux-gnu
          cp aarch64.config ${{ env.LINUX_PATH }}/.config

          sudo mkdir -p ${{ env.TARGET_PATH }}/boot

      - name: Build and install the kernel
        working-directory: ${{ env.LINUX_PATH }}
        run: |
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j8
          sudo make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
            install dtbs_install modules_install \
            INSTALL_PATH=../${{ env.TARGET_PATH }}/boot \
            INSTALL_MOD_PATH=../${{ env.TARGET_PATH }}
          sudo rm ../${{ env.TARGET_PATH }}/lib/modules/*/{build,source}

      - name: Package the built kernel
        working-directory: ${{ env.TARGET_PATH }}
        run: |
          sudo tar zcf ../kernel-aarch64.tar.gz *
          sudo chmod a+r ../kernel-aarch64.tar.gz

      - name: Upload compressed kernel
        if: startsWith(github.ref, 'refs/tags/') == false
        uses: actions/upload-artifact@v2
        with:
          name: kernel-aarch64.tar.gz
          path: kernel-aarch64.tar.gz

      - name: Calculate hash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sha512sum kernel-aarch64.tar.gz > sha512.sum

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kernel-aarch64.tar.gz
            sha512.sum
