name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, riscv64]
    env:
      KERNEL_REPO: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
      KERNEL_VER: 'v6.3.1'
      LINUX_PATH: 'linux'
      TARGET_PATH: 'kernel_${{ matrix.arch }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Linux stable kernel
        run: |
          git clone --branch ${{ env.KERNEL_VER }} --depth 1 ${{ env.KERNEL_REPO }} ${{ env.LINUX_PATH }}

      - name: Prepare build environment
        run: |
          sudo apt update -y
          sudo apt install gcc-${{ matrix.arch }}-linux-gnu -y

          # gcc-{matrix.arch}-linux-gnu
          cp ${{ matrix.arch }}.config ${{ env.LINUX_PATH }}/.config

          sudo mkdir -p ${{ env.TARGET_PATH }}/boot

      - name: Build and install the kernel
        working-directory: ${{ env.LINUX_PATH }}
        run: |
          case "${{ matrix.arch }}" in
            aarch64) arch='arm64' ;;
            riscv64) arch='riscv' ;;
          esac

          make ARCH=${arch} CROSS_COMPILE=${{ matrix.arch }}-linux-gnu- -j8
          sudo make ARCH=${arch} CROSS_COMPILE=${{ matrix.arch }}-linux-gnu- \
            install dtbs_install modules_install \
            INSTALL_PATH=../${{ env.TARGET_PATH }}/boot \
            INSTALL_MOD_PATH=../${{ env.TARGET_PATH }}
          sudo rm ../${{ env.TARGET_PATH }}/lib/modules/*/{build,source}

      - name: Package the built kernel
        working-directory: ${{ env.TARGET_PATH }}
        run: |
          sudo tar zcf ../kernel-${{ matrix.arch }}.tar.gz *
          sudo chmod a+r ../kernel-${{ matrix.arch }}.tar.gz

      - name: Upload compressed kernel
        if: startsWith(github.ref, 'refs/tags/') == false
        uses: actions/upload-artifact@v3
        with:
          name: kernel-${{ matrix.arch }}.tar.gz
          path: kernel-${{ matrix.arch }}.tar.gz

      - name: Calculate hash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sha512sum kernel-${{ matrix.arch }}.tar.gz > ${{ matrix.arch }}.sha512.sum

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kernel-${{ matrix.arch }}.tar.gz
            ${{ matrix.arch }}.sha512.sum
